/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caldinho.ja.views;

import caldinho.ja.escopo.Caldinho;
import caldinho.ja.escopo.AboboraCarne;
import caldinho.ja.escopo.CaldoVerde;
import caldinho.ja.escopo.Canja;
import caldinho.ja.escopo.Ervilha;
import caldinho.ja.escopo.Feijao;
import caldinho.ja.escopo.MandioqAlhoPorro;
import caldinho.ja.escopo.Palmito;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LuizGuilherme
 */
public class CardLayoutFrame extends javax.swing.JFrame {

    /**
     * Creates new form CardLayoutFrame
     */
    public CardLayoutFrame() {
        initComponents();
    }
    public String cardname = "index";
    String ingredientesCaldoVerde, ingredientesMandioqAlhoPoro, ingredientesAboboraCarne, ingredientesPalmito, ingredientesFeijao, ingredientesCanja, ingredientesErvilha;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paiPanel = new javax.swing.JPanel();
        indexPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        estoquePnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clientesPnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        vendasPnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        receitasPnl = new javax.swing.JPanel();
        receitasCardsPnl = new javax.swing.JPanel();
        receitasPnlCaldoVerde = new javax.swing.JPanel();
        nomeCaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientesText = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        passosText = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        receitaComboBox = new javax.swing.JComboBox();
        fotosCaldos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        estoqueBtn = new javax.swing.JButton();
        clientesBtn = new javax.swing.JButton();
        vendasBtn = new javax.swing.JButton();
        receitasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALDINHO JÁ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        paiPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        paiPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/caldinhojagrande.jpg"))); // NOI18N

        javax.swing.GroupLayout indexPnlLayout = new javax.swing.GroupLayout(indexPnl);
        indexPnl.setLayout(indexPnlLayout);
        indexPnlLayout.setHorizontalGroup(
            indexPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexPnlLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        indexPnlLayout.setVerticalGroup(
            indexPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        paiPanel.add(indexPnl, "index");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESTOQUE");

        javax.swing.GroupLayout estoquePnlLayout = new javax.swing.GroupLayout(estoquePnl);
        estoquePnl.setLayout(estoquePnlLayout);
        estoquePnlLayout.setHorizontalGroup(
            estoquePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estoquePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        estoquePnlLayout.setVerticalGroup(
            estoquePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estoquePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(668, Short.MAX_VALUE))
        );

        paiPanel.add(estoquePnl, "estoque");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLIENTES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Apartamento", "Telefone"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton2.setText("Novo");

        jTextField1.setToolTipText("Pesquisa...");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton3.setText("Busca");

        javax.swing.GroupLayout clientesPnlLayout = new javax.swing.GroupLayout(clientesPnl);
        clientesPnl.setLayout(clientesPnlLayout);
        clientesPnlLayout.setHorizontalGroup(
            clientesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                    .addGroup(clientesPnlLayout.createSequentialGroup()
                        .addGroup(clientesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(clientesPnlLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        clientesPnlLayout.setVerticalGroup(
            clientesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(clientesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(clientesPnlLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(clientesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        paiPanel.add(clientesPnl, "clientes");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VENDAS");

        javax.swing.GroupLayout vendasPnlLayout = new javax.swing.GroupLayout(vendasPnl);
        vendasPnl.setLayout(vendasPnlLayout);
        vendasPnlLayout.setHorizontalGroup(
            vendasPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendasPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        vendasPnlLayout.setVerticalGroup(
            vendasPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendasPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(668, Short.MAX_VALUE))
        );

        paiPanel.add(vendasPnl, "vendas");

        nomeCaldo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nomeCaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeCaldo.setText("Caldo Verde");

        ingredientesText.setEditable(false);
        ingredientesText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(ingredientesText);

        passosText.setEditable(false);
        passosText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(passosText);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ingredientes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Passo-a-passo");

        javax.swing.GroupLayout receitasPnlCaldoVerdeLayout = new javax.swing.GroupLayout(receitasPnlCaldoVerde);
        receitasPnlCaldoVerde.setLayout(receitasPnlCaldoVerdeLayout);
        receitasPnlCaldoVerdeLayout.setHorizontalGroup(
            receitasPnlCaldoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receitasPnlCaldoVerdeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receitasPnlCaldoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receitasPnlCaldoVerdeLayout.createSequentialGroup()
                        .addGroup(receitasPnlCaldoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(receitasPnlCaldoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        receitasPnlCaldoVerdeLayout.setVerticalGroup(
            receitasPnlCaldoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receitasPnlCaldoVerdeLayout.createSequentialGroup()
                .addComponent(nomeCaldo)
                .addGap(22, 22, 22)
                .addGroup(receitasPnlCaldoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receitasPnlCaldoVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );

        javax.swing.GroupLayout receitasCardsPnlLayout = new javax.swing.GroupLayout(receitasCardsPnl);
        receitasCardsPnl.setLayout(receitasCardsPnlLayout);
        receitasCardsPnlLayout.setHorizontalGroup(
            receitasCardsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receitasPnlCaldoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        receitasCardsPnlLayout.setVerticalGroup(
            receitasCardsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receitasPnlCaldoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        receitaComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        receitaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caldo Verde", "Abóbora com Carne", "Mandioquinha com Alho Poró", "Palmito", "Canja de Galinha", "Ervilha", "Feijão" }));
        receitaComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        receitaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitaComboBoxActionPerformed(evt);
            }
        });

        fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/CaldoVerde.jpg"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("FAZER SOPA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receitasPnlLayout = new javax.swing.GroupLayout(receitasPnl);
        receitasPnl.setLayout(receitasPnlLayout);
        receitasPnlLayout.setHorizontalGroup(
            receitasPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receitasPnlLayout.createSequentialGroup()
                .addGroup(receitasPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receitasPnlLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(receitasPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fotosCaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receitasPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(receitaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receitasCardsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        receitasPnlLayout.setVerticalGroup(
            receitasPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receitasPnlLayout.createSequentialGroup()
                .addComponent(receitasCardsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addGroup(receitasPnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(receitaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(fotosCaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paiPanel.add(receitasPnl, "receitas");

        estoqueBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        estoqueBtn.setText("ESTOQUE");
        estoqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueBtnestoqueActionPerformed(evt);
            }
        });

        clientesBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clientesBtn.setText("CLIENTES");
        clientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBtnclientesActionPerformed(evt);
            }
        });

        vendasBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vendasBtn.setText("VENDAS");
        vendasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasBtnvendasActionPerformed(evt);
            }
        });

        receitasBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        receitasBtn.setText("RECEITAS");
        receitasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitasBtnreceitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(paiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estoqueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receitasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clientesBtn, estoqueBtn, receitasBtn, vendasBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estoqueBtn)
                    .addComponent(clientesBtn)
                    .addComponent(vendasBtn)
                    .addComponent(receitasBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estoqueBtnestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueBtnestoqueActionPerformed
        CardLayout card = (CardLayout) paiPanel.getLayout();
        if (cardname.equals("estoque")) {
            cardname = "index";
            estoqueBtn.setBackground(Color.LIGHT_GRAY);
        } else {
            cardname = "estoque";
            estoqueBtn.setBackground(Color.GRAY);
            clientesBtn.setBackground(Color.LIGHT_GRAY);
            vendasBtn.setBackground(Color.LIGHT_GRAY);
            receitasBtn.setBackground(Color.LIGHT_GRAY);
        }
        card.show(paiPanel, cardname);
    }//GEN-LAST:event_estoqueBtnestoqueActionPerformed

    private void clientesBtnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBtnclientesActionPerformed
        CardLayout card = (CardLayout) paiPanel.getLayout();
        if (cardname.equals("clientes")) {
            cardname = "index";
            clientesBtn.setBackground(Color.LIGHT_GRAY);
        } else {
            cardname = "clientes";
            estoqueBtn.setBackground(Color.LIGHT_GRAY);
            clientesBtn.setBackground(Color.GRAY);
            vendasBtn.setBackground(Color.LIGHT_GRAY);
            receitasBtn.setBackground(Color.LIGHT_GRAY);
        }
        card.show(paiPanel, cardname);
    }//GEN-LAST:event_clientesBtnclientesActionPerformed

    private void vendasBtnvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasBtnvendasActionPerformed
        CardLayout card = (CardLayout) paiPanel.getLayout();
        if (cardname.equals("vendas")) {
            cardname = "index";
            vendasBtn.setBackground(Color.LIGHT_GRAY);
        } else {
            cardname = "vendas";
            card.show(paiPanel, cardname);
            estoqueBtn.setBackground(Color.LIGHT_GRAY);
            clientesBtn.setBackground(Color.LIGHT_GRAY);
            vendasBtn.setBackground(Color.GRAY);
            receitasBtn.setBackground(Color.LIGHT_GRAY);
        }
        card.show(paiPanel, cardname);
    }//GEN-LAST:event_vendasBtnvendasActionPerformed

    private void receitasBtnreceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitasBtnreceitasActionPerformed
        CardLayout card = (CardLayout) paiPanel.getLayout();
        if (cardname.equals("receitas")) {
            cardname = "index";
            receitasBtn.setBackground(Color.LIGHT_GRAY);
        } else {
            cardname = "receitas";
            estoqueBtn.setBackground(Color.LIGHT_GRAY);
            clientesBtn.setBackground(Color.LIGHT_GRAY);
            vendasBtn.setBackground(Color.LIGHT_GRAY);
            receitasBtn.setBackground(Color.GRAY);
        }
        card.show(paiPanel, cardname);
        
        ingredientesCaldoVerde = ""; ingredientesMandioqAlhoPoro = ""; ingredientesAboboraCarne = ""; ingredientesPalmito = ""; ingredientesFeijao = ""; ingredientesCanja = ""; ingredientesErvilha = "";
        for (int i = 0; i < CaldoVerde.getIngredientes().size(); i++) {
            ingredientesCaldoVerde += (i + 1) + ". " + CaldoVerde.getIngredientes().get(i).getNome() + " - " + (int) CaldoVerde.getIngredientes().get(i).getQtd() + " " + CaldoVerde.getIngredientes().get(i).getUnidade() + "\n\n";
            ingredientesMandioqAlhoPoro += (i + 1) + ". " + MandioqAlhoPorro.getIngredientes().get(i).getNome() + " - " + (int) MandioqAlhoPorro.getIngredientes().get(i).getQtd() + " " + MandioqAlhoPorro.getIngredientes().get(i).getUnidade() + "\n\n";
            ingredientesAboboraCarne += (i + 1) + ". " + AboboraCarne.getIngredientes().get(i).getNome() + " - " + (int) AboboraCarne.getIngredientes().get(i).getQtd() + " " + AboboraCarne.getIngredientes().get(i).getUnidade() + "\n\n";
            ingredientesPalmito += (i + 1) + ". " + Palmito.getIngredientes().get(i).getNome() + " - " + (int) Palmito.getIngredientes().get(i).getQtd() + " " + Palmito.getIngredientes().get(i).getUnidade() + "\n\n";
            ingredientesFeijao += (i + 1) + ". " + Feijao.getIngredientes().get(i).getNome() + " - " + (int) Feijao.getIngredientes().get(i).getQtd() + " " + Feijao.getIngredientes().get(i).getUnidade() + "\n\n";
            ingredientesCanja += (i + 1) + ". " + Canja.getIngredientes().get(i).getNome() + " - " + (int) Canja.getIngredientes().get(i).getQtd() + " " + Canja.getIngredientes().get(i).getUnidade() + "\n\n";
            ingredientesErvilha += (i + 1) + ". " + Ervilha.getIngredientes().get(i).getNome() + " - " + (int) Ervilha.getIngredientes().get(i).getQtd() + " " + Ervilha.getIngredientes().get(i).getUnidade() + "\n\n";

        }
        if(receitaComboBox.getSelectedIndex()==0){
            ingredientesText.setText(ingredientesCaldoVerde);
            passosText.setText(CaldoVerde.getReceita());
            nomeCaldo.setText("Caldo Verde");
        }

    }//GEN-LAST:event_receitasBtnreceitasActionPerformed

    private void receitaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitaComboBoxActionPerformed

        String selected = "";
        switch (receitaComboBox.getSelectedIndex()) {
            case 0:
                selected = "receitaCaldoVerde";
                fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/CaldoVerde.jpg")));
                ingredientesText.setText(ingredientesCaldoVerde);
                passosText.setText(CaldoVerde.getReceita());
                nomeCaldo.setText("Caldo Verde");
                break;
            case 1:
                selected = "receitaAboboraCarne";
                fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/AboboraCarne.jpg")));
                ingredientesText.setText(ingredientesAboboraCarne);
                passosText.setText(AboboraCarne.getReceita());
                nomeCaldo.setText("Sopa de Abóbora com Carne");
                break;
            case 2:
                selected = "receitaMandioqAlhoPoro";
                fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/MandioqAlhoPoro.jpg")));
                ingredientesText.setText(ingredientesMandioqAlhoPoro);
                passosText.setText(MandioqAlhoPorro.getReceita());
                nomeCaldo.setText("Sopa de Mandioquinha com Alho Poró");
                break;
            case 3:
                selected = "receitaPalmito";
                fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/Palmito.jpg")));
                ingredientesText.setText(ingredientesPalmito);
                passosText.setText(Palmito.getReceita());
                nomeCaldo.setText("Creme de Palmito");
                break;
            case 4:
                selected = "receitaCanja";
                fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/Canja.jpg")));
                ingredientesText.setText(ingredientesCanja);
                passosText.setText(Canja.getReceita());
                nomeCaldo.setText("Canja de Galinha");
                break;
            case 5:
                selected = "receitaErvilha";
                fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/Ervilha.jpg")));
                ingredientesText.setText(ingredientesErvilha);
                passosText.setText(Ervilha.getReceita());
                nomeCaldo.setText("Creme de Ervilha");
                break;
            case 6:
                selected = "receitaFeijao";
                fotosCaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caldinho/ja/images/Feijao.jpg")));
                ingredientesText.setText(ingredientesFeijao);
                passosText.setText(Feijao.getReceita());
                nomeCaldo.setText("Caldinho de Feijão");
                break;
        }


    }//GEN-LAST:event_receitaComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Caldinho sopa = null;
        switch (receitaComboBox.getSelectedIndex()) {
            case 0:
                sopa = new CaldoVerde();
                break;
            case 1:
                sopa = new AboboraCarne();
                break;
            case 2:
                sopa = new MandioqAlhoPorro();
                break;
            case 3:
                sopa = new Palmito();
                break;
            case 4:
                sopa = new Canja();
                break;
            case 5:
                sopa = new Ervilha();
                break;
            case 6:
                sopa = new Feijao();
                break;
        }
        sopa.fazCaldo(Float.parseFloat(JOptionPane.showInputDialog("Informe a quantidade de " + nomeCaldo.getText() + " que será feita")));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardLayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardLayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardLayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardLayoutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardLayoutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientesBtn;
    private javax.swing.JPanel clientesPnl;
    private javax.swing.JButton estoqueBtn;
    private javax.swing.JPanel estoquePnl;
    private javax.swing.JLabel fotosCaldos;
    private javax.swing.JPanel indexPnl;
    private javax.swing.JTextPane ingredientesText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nomeCaldo;
    private javax.swing.JPanel paiPanel;
    private javax.swing.JTextPane passosText;
    private javax.swing.JComboBox receitaComboBox;
    private javax.swing.JButton receitasBtn;
    private javax.swing.JPanel receitasCardsPnl;
    private javax.swing.JPanel receitasPnl;
    private javax.swing.JPanel receitasPnlCaldoVerde;
    private javax.swing.JButton vendasBtn;
    private javax.swing.JPanel vendasPnl;
    // End of variables declaration//GEN-END:variables
}
