/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caldinho.ja.views;

import caldinho.ja.dao.ClienteDAOImpl;
import caldinho.ja.dao.FonteDados;
import caldinho.ja.escopo.Cliente;
import java.awt.event.ActionEvent;
import javax.persistence.EntityManager;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author luiz
 */
public class EditDeleteCliente extends javax.swing.JPanel {

    /**
     * Creates new form EditDeleteCliente
     */
    EntityManager em = FonteDados.createEntityManager();
    ClienteDAOImpl cdao = new ClienteDAOImpl(em);

    public EditDeleteCliente(int ID) {
        initComponents();

        Cliente cliente = cdao.getCliente(ID);
        idField.setText(String.valueOf(cliente.getCliente_id()));
        nomeTextField.setText(cliente.getNome());
        enderecoTextField.setText(cliente.getEndereco());
        apartamentoField.setText(cliente.getApartamento());
        telefoneField.setText(String.valueOf(cliente.getDdd()) + String.valueOf(cliente.getTelefone()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTextField = new javax.swing.JTextField();
        enderecoTextField = new javax.swing.JTextField();
        apartamentoField = new javax.swing.JTextField();
        telefoneField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alteraClienteBtn = new javax.swing.JButton();
        deleteClienteBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        idField = new javax.swing.JTextField();

        jLabel1.setText("Nome");

        jLabel2.setText("Endereço");

        jLabel3.setText("Apartamento");

        jLabel4.setText("Telefone");

        alteraClienteBtn.setText("Alterar");
        alteraClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraClienteBtnActionPerformed(evt);
            }
        });

        deleteClienteBtn.setText("Remover");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        idField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(85, Short.MAX_VALUE)
                        .addComponent(alteraClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTextField)
                            .addComponent(enderecoTextField)
                            .addComponent(apartamentoField)
                            .addComponent(telefoneField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apartamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alteraClienteBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteClienteBtn)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alteraClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraClienteBtnActionPerformed
        Cliente cliente = cdao.getCliente(Integer.parseInt(idField.getText()));
        cliente.setNome(nomeTextField.getText().toUpperCase());
        if (enderecoTextField.getText().isEmpty()) {
            cliente.setEndereco("CLIENTE INTERNO");
            cliente.setInterno(true);
        } else {
            cliente.setEndereco(enderecoTextField.getText().toUpperCase());
            cliente.setInterno(false);
        }
        cliente.setApartamento(apartamentoField.getText().toUpperCase());
        if (telefoneField.getText().length() >= 10) {
            cliente.setDdd(Integer.parseInt(telefoneField.getText().substring(0, 2)));
            cliente.setTelefone(Integer.parseInt(telefoneField.getText().substring(2)));
        } else {
            cliente.setDdd(11);
            cliente.setTelefone(Integer.parseInt(telefoneField.getText()));
        }
        ClienteDAOImpl clienteDAO = new ClienteDAOImpl(em);
        clienteDAO.atualizaCliente(cliente);
    }//GEN-LAST:event_alteraClienteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alteraClienteBtn;
    private javax.swing.JTextField apartamentoField;
    private javax.swing.JButton deleteClienteBtn;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField telefoneField;
    // End of variables declaration//GEN-END:variables
}
